export type GitOperationOptions = {
  repo_root?: string;
  path?: string;
  old_path?: string;
  message?: string;
  remote_url?: string;
  branch?: string;
  branch_kind?: "local" | "remote";
  new_branch?: string;
  start_point?: string;
  post_action?: "push" | "sync";
  patch?: string;
  commit?: string;
  reset_mode?: "soft" | "mixed" | "hard";
  stash_ref?: string;
  tag?: string;
  remote_name?: string;
  worktree_path?: string;
  include_untracked?: boolean;
  resolution?: "ours" | "theirs" | "content";
  content?: string;
  all?: boolean;
  amend?: boolean;
  signoff?: boolean;
  force?: boolean;
};
