mod binary;
pub(crate) mod commands;
mod config;
mod discovery;
mod events;
mod file_ops;
mod grants;
mod host;
mod http;
pub(crate) mod knowledge_view;
pub(crate) mod legacy_alarm_jobs;
mod lock_file;
mod management;
mod management_lock;
mod notification;
pub(crate) mod operation;
mod package_archive;
mod presentation;
mod private;
mod registry;
pub(crate) mod scheduler;
mod services;
mod session;
mod system;
pub(crate) mod todo_view;

pub(crate) use discovery::{discover, PluginDiagnostic, PluginSource};
pub(crate) use events::PluginEvents;
pub(crate) use grants::{GrantChanges, GrantUpdate};
pub(crate) use legacy_alarm_jobs::run_worker as run_legacy_alarm_worker;
pub(crate) use management::{configure, install, remove, scaffold, set_enabled, validate_package};
pub(crate) use package_archive::pack;
pub(crate) use presentation::notification_plan;
pub(crate) use private::clear_session_storage;
pub(crate) use registry::register_plugins;
pub(crate) use services::{PluginModelSource, PluginServices, PluginVisionSource};
pub(crate) use session::PluginSession;

#[cfg(test)]
mod tests;
